### ISSUE TITLE
"HEBREW POINT QAMATS QATAN" has been force cast into an ordinary "HEBREW POINT QAMATS"

### ISSUE THREAD

**Issue by etayluz** [akivajgordon/tikkun.io#100]
In tikkun.io - Genesis 1:21 - what should be a "HEBREW POINT QAMATS QATAN" under the letter KAF has apparently been force cast into an ordinary: "HEBREW POINT QATAN"
![image](https://user-images.githubusercontent.com/1825834/143308721-70274394-af1f-41cf-b750-c615cf2c1cb0.png)

However on Sefaria it appears correctly as such:
https://www.sefaria.org/Genesis.1.21
![image](https://user-images.githubusercontent.com/1825834/143309019-b3d0e8fa-3528-4186-8977-d8435d338f9d.png)

Any native Hebrew speaker will know that Sefaria's version is correct.
The QAMATS QATAN is pronounced very differently than an ordinary QATAN.

While they look almost identical, the QAMATS QATAN has a slightly longer stem than the ordinary QAMATS. But it's an entirely different vowel and it's critical to distinguish between the two.

What is the source of the text?
I would not recommend using it.

**Comment by akivajgordon** [comment]
@etayluz – thanks for creating this issue!

Ironically, the source text is from Sefaria, e.g.: https://github.com/Sefaria/Sefaria-Export/blob/master/json/Tanakh/Torah/Genesis/Hebrew/Tanach%20with%20Ta'amei%20Hamikra.json

But unfortunately, it seems that they don't have the kamatz katan there. The Sefaria website might be using a different version of source text that I haven't found. If you know how to get that source text as something machine parsable, like JSON, I would love if you could point me to that. The kamatz katan issue has been bothering me for a long time, too.

Since there is already an issue to track this in #44, I will close this issue here and we can continue to track the issue over there. This issue will be referenced over there, so we won't lose anything. 

Thanks again!

**Comment by etayluz** [comment]
I'll put together a nice json file and attach it later. It will just be a copy and paste of the content from Sefaria's website. It seems to be the most authoritative Mesoratic text.
