### ISSUE TITLE
Erroneous Aliyah indicator

### ISSUE THREAD

**Issue by JackYoungblood** [akivajgordon/tikkun.io#11]
There's an indicator that the shvi'i aliyah of Emor begins at Vayikra 24:23 instead of at 24:1 where I believe it belongs

**Comment by akivajgordon** [comment]
Wow, that's terrible. So sorry about that – thanks for catching it! I'm not sure why that happened, but it's definitely something I would like to look into and fix.

Sorry development has been slow 😞. I'm very passionate about this project (I am an avid user, since I read almost every week, exclusively from this), so I definitely intend to continue working on it. I'm just juggling a lot right now, but things should open up for me soon, B"H.

**Comment by JackYoungblood** [comment]
Lol, I hope that wasn't a real apology. Your tikkun.io is by far the best online tikkun available. If I spot an error every once in a while it's not a big deal. 

As for development, I'm sure you'll get to things as time allows. If you're reading a full parasha every week I'm sure that already claims a good chunk of your time.

**Comment by akivajgordon** [comment]
Thanks, I really appreciate the encouraging feedback.

Becoming an abba for the first time has been the biggest "usage of my CPU cycles", if you know what I mean 😉. Wouldn't trade it for anything, but I'm just saying...
