### ISSUE TITLE
Bookmark sections

### ISSUE THREAD

**Issue by binyamin** [akivajgordon/tikkun.io#64]
**Description:** A frequent leiner may want to bookmark a couple locations, for easy switching and finding.

**Notes**
The implementation could include an array of locations kept in Local Storage. It would be similar to #39. For the design, something similar to this :point_down: might work.
![image](https://user-images.githubusercontent.com/39805353/83972478-62961400-a8ae-11ea-8acd-4243c92ef84d.png)

**Comment by binyamin** [comment]
One problem I foresee is that there doesn't seem to be any id to link to.
To solve this, we could create an id for each line in the form of `#<sefer>:<perek>:<posuk>`. For example, בראשית ז' א would be `#1:7:1`. In general, I think section linking can be a useful feature.

**Comment by akivajgordon** [comment]
@b3u Thanks for submitting the issue! And thanks for the visual to help me better understand what you're looking for.

It's something I've thought about before. You wrote:

> A frequent leiner may want to bookmark a couple locations, for easy switching and finding.

 Could you share a more details about the use case? What might the frequent reader be switching between? I'm trying to better understand the issue before jumping to a specific solution.

**Comment by binyamin** [comment]
> Could you share a more details about the use case?

@akivajgordon Sure. I may be (1) practicing a parsha a couple weeks in advance, (2) going over the weekly parsha while I'm in front of a tikkun, and (3) reviewing the reading _and_ the maftir for an upcoming holiday. Admittedly, 1 and 2 are placed near each other, while 3 can be solved by adding hints for special readings.

Another example is someone preparing for Megillas Esther. They want to be well prepared, as it is a long reading, but they also want to lein a parsha a month or so beforehand.

**Comment by akivajgordon** [comment]
Thanks for elaborating.

For all of those use cases, except for (3), I don't think it's worth adding additional UI in order to jump around – I think the current way isn't too much friction to finding a parsha, especially with the fuzzy search that a frequent reader would discover naturally.

As for (3), I plan to be adding all of the holiday readings as well in a similar manner to how the rest are displayed today. Again, not too much friction if you ask me.

E.g. I want to jump between Esther and Matot - to get to Esther, I type <kbd>/</kbd> to bring up the navigation, then "Est" <kbd>Enter</kbd>, then back to Matot with <kbd>/</kbd>mat<kbd>Enter</kbd>. It's pretty quick. Even just finding it from the list isn't too much of a struggle in my opinion.

Sorry if it sounds like I'm dismissing the idea too much, but this feels like a feature whose upside is too minimal to warrant additional UI. I'm not opposed to adding new UI, but since there will undoubtedly be more, I'd want to limit it to where it really needs to be there.

I love your enthusiasm with the features though, so please keep them coming!

Closing for now, but happy to continue the discussion and I'm willing to re-open if the use-case is there.
