### ISSUE TITLE
Direct links to specific parsha/section

### ISSUE THREAD

**Issue by Chajmke** [akivajgordon/tikkun.io#65]
I recently embedded the (great - yasher koach!) tool to our website and what would be marvelous, is some kind of deep linking into the different parashot via an URL parameter/argument. Or is it already implemented and I wasn't able to figure this out?

**Comment by akivajgordon** [comment]
Thanks for opening this issue and for the kind words!

This is not possible today, but it is one of the next items on my list to do. In fact, I'll use this issue to continue tracking it, as well as request feedback on the implementation.

Thanks again, and stay tuned.

**Comment by akivajgordon** [comment]
Just throwing out some ideas (notes) about how this might be implemented. Happy to hear feedback.

Since this is a completely static site (no backend), all routing will be done client side after the hash. Here are some examples of ways I'm thinking about deep linking:

* `https://www.tikkun.io/#/p/shoftim` (anything after /p/ will parse as a parsha to jump to)
* `https://www.tikkun.io/#/p/שופטים` (can accept Hebrew as well)
* `https://www.tikkun.io/#/r/1-4-19` (jump to any "reference", i.e. book-chapter-verse)
* `https://www.tikkun.io/#/next` (quick link to jump to the next upcoming reading)
* `https://www.tikkun.io/#/q/vayish` (maybe pre-fills search with "vayish"?)

This set above doesn't account for:

* jumping to Esther
* special holidays (which have not yet been added to the tikkun in general, but it's in the pipeline...)

**Comment by Chajmke** [comment]
I like the idea(s), once the syntax is known, it should be simple to link.

How do you deal with ”two words“ parashot like Chaye Sara? Underscore?

**Comment by akivajgordon** [comment]
@talmudde I was thinking of making it as flexible as possible by using some closest match type of algorithm. Nothing too fancy, but it would be ideal if it accepted "chayei-sara" or "chayeh_sarah" or "חיישרה" or "חיי%20שרה" or anything similar. At the minimum, I could strip out any non-alpha (Hebrew or English) characters to reduce the number of possible variations.

I could also just match the query against a whitelist of possible spellings, and then be on the lookout in analytics for ones that users entered but didn't match at all. I could then add those spellings to the whitelist. It's probably an easier first start.

Also, I'm not sure how much it will matter anyway, because I imagine the most common use case would be to bookmark, so what you'd probably do is navigate to the parsha in the app, and then observe what the URL changes to in the address bar, and then just copy that for the bookmark.

**Comment by Chajmke** [comment]
You are right - in order to generate the direct links, most people would do the ”copy and paste“ job…

**Comment by binyamin** [comment]
@akivajgordon Since the site is displayed as a single document, I think we should use hashes or url params instead of routing. Something like `https://tikkun.io/#1:12:1` or `https://tikkun.io/?q=vayish` might make more sense to a user.

**Comment by akivajgordon** [comment]
@binyamin – I'm about a year late to reply to your comment (I never saw it, sorry!).

In my proposals [above](https://github.com/akivajgordon/tikkun.io/issues/65#issuecomment-643447000), I had prefixed everything with a hash along the same lines of your thoughts. Am I misunderstanding your suggestion, or did you not notice the hashes there?

**Comment by binyamin** [comment]
@akivajgordon It's totally fine! My intent with that comment was that, slashes in a url usually denote the path to a page with a hierarchy. The tikkun is essentially one long document, so url fragments (`/#id`) might feel more natural than paths (`/#/id`). That was what I meant with https://github.com/akivajgordon/tikkun.io/issues/65#issuecomment-645026144

However, I don't like the idea of having every link appear as the same page. Ideally, the URL structure would mimic the content structure.

(new suggestion coming)

**Comment by binyamin** [comment]
Honestly, the easiest solution might be to have a `/go` endpoint which would redirect to a parsha, a reference, a holiday, or even an aliyah (eg. `/go?parsha=foo` or `/go?ref=1:4:19`). I do think there should be a separate path for every megillah, and for the chumash/torah.

Personally, I think the issue here is that a real tikkun has multiple pages, and a sefer torah has multiple columns, but the website is one long document. Therefore, any path hierarchy (`/foo/bar`) looks wrong, because it's clearly not a separate page.

Instead of having a single continuous page, maybe each parsha has a separate page. Because the content is rendered dynamically, you could show the same content at the end on one parsha and at the start of the next. Imho, it's much easier to think of a parsha page, than to think of a link to the middle of a gigantic document. Basically, it would be `/vayeishev`, and maybe `/vayeishev#sheni`. I'm not sure whether each column would be it's own page (`/vayeishev/1`), with buttons to "turn the page".

**Comment by binyamin** [comment]
Btw, I spent _way_ too much time thinking about this issue :sweat_smile:. If you're open to it, I'd love to do a virtual meeting.
