### ISSUE TITLE
Layout Bug: Incorrect Setuma at beginning of Vayigash

### ISSUE THREAD

**Issue by JackYoungblood** [akivajgordon/tikkun.io#8]
There issupposed to be a setumah from the end of Miketz into the beginning of Vayigash. But the web site currently shows the end of Miketz rolling right into the first two words Vayigash followed by a petucha.

**Comment by akivajgordon** [comment]
This is actually occurring because of incorrect setuma/petucha values from the source where I got the text. Right now, these occur throughout, and I have to go manually find each one. I've made a number of these corrections so far and I hope to be able to push an update soon to fix as many as I can find. Thanks for reporting this.
